### ISSUE TITLE
Query about future feature release

### ISSUE THREAD

**Issue by LiorHaim** [solydhq/plugin-mattermost#11]
Hello,

Our group uses the lyno mattermost plugin for a few weeks an find it extremely useful.

I don't know if the plugin development is still active - but the list of future feature release is becoming crucial for us.
( https://github.com/lynoapp/mattermost-plugin-lyno#future-features )
Is there any progress regarding these features? any estimation to a new release?

Thank you.

**Comment by sapkra** [comment]
We have discussed it internally and decided to invest more time into the plugin, also because lots of our users are coming from it. We think that we will start with continuing the development in the beginning of 2022.

**Comment by LiorHaim** [comment]
@sapkra amazing news!
Thank you for the update!

**Comment by LiorHaim** [comment]
Hey,
Any news? 🙏

**Comment by sapkra** [comment]
@LiorHaim Yes, our plan is to relaunch the extension in February.
