### ISSUE TITLE
lyno voice rooms mattermost plugin not connecting with solyd (lyno.io)

### ISSUE THREAD

**Issue by NexusEFR** [solydhq/plugin-mattermost#13]
Are the lyno servers working?

**Comment by sapkra** [comment]
Yes, they are working but unfortunately we made a breaking change in our API which requires an update of our plugin. We are currently working on a new release.

**Comment by sapkra** [comment]
I created a new release which theoretically should work but I have not tested it yet, because I need to setup a mattermost server for that. I will do that tomorrow but feel free to test it yourself. I'm open for your feedback.

https://github.com/solydhq/plugin-mattermost/releases/tag/v3.3.5

**Comment by NexusEFR** [comment]
Great, thank you very much for the quick response! People like you are appreciated... Although I do not get the plugin to work, since I have tried to remove lyno plugin before and put it later, or install it after it was installed lyno, so I do not understand well if it is an update or a new plugin, should both be installed and activated or what is the correct way to install? No voice channel or header of solyd channels appears, only of lyno but without working equally.

Anyway your effort is well received, I can wait for you to do your tests and get the functional version.

Best regards

**Comment by sapkra** [comment]
Thank you for trying it out.

I tested it myself now and yeah, there were still some errors. I fixed them and updated the release. I also added some upgrade instructions to the readme.

Please remove all lyno and solyd plugins, install the new one and active it. I'm still not done with the entire test because setting up everything to test this plugin is quite complicated. I would very appreciate your feedback on the hopefully fixed version.

**Comment by NexusEFR** [comment]
Hi Paul. Thank you again for your efforts, I know they are complicated jobs. 
The fact is that now if the header of the channels appears but does not load the standard channels. I removed Lyno, restarted, updated Mattermost to 6.4 and installed Solyd but it still doesn't work. 
I follow the recommendations of your installation:
I have a server with domain and SSL certificate (R3 from LetsEncrypt) with the Omnibus script to install Mattermost on Ubuntu.
Developer mode disabled
Reachable from the internet, although I have to mention that my port is redirected from an external NAT 2445 to 443, which Nginx works well. 
Before it worked with these same configurations with Lyno, so I understand that everything is ok on my part.

I hope we can advance in it, this plugin has a lot of future in Mattermost at a collaborative level.

Best regards

**Comment by chfxr** [comment]
Its still not working for us - no channels are shown.

**Comment by sapkra** [comment]
@chfxr @NexusEFR Sorry for the delay. I finally had some time to figure it out. The plugin should finally work again using [v3.3.6](https://github.com/solydhq/plugin-mattermost/releases/tag/v3.3.6). If you still have any problem just reach out.
