### ISSUE TITLE
Downtime due to backend changes this week

### ISSUE THREAD

**Issue by sapkra** [solydhq/plugin-mattermost#15]
We are dramatically changing our backend right now to decrease infrastructure costs and maintenance overhead as well as improving the stability. Due to these changes our service might have some issues within the next days. Please subscribe to this issue. I will let you know.

**Comment by tonytonyistony** [comment]
Upon enter a channel causes the Mattermost client to go white. Force restart of the app is required to regain functionality.

**Comment by sapkra** [comment]
Working on a new version to fix it.

**Comment by sapkra** [comment]
I released a [new version](https://github.com/solydhq/plugin-mattermost/releases/tag/v4.2.0). You are now even able to see the mute status of all participants.

@tonytonyistony Can you try it out? I would very appreciate your feedback.

**Comment by tonytonyistony** [comment]
Sorry Paul. I have uninstalled Mattermost and have move full time to Matrix.

**Comment by sapkra** [comment]
That's fine. I hope you will have a great experience going forward with it.

solyd is a freemium service, but we were not able to make it profitable to put all our development resources in it. So the plugin development is way behind our main product.
